### ISSUE TITLE
Add option "Keep open"

### ISSUE THREAD

**Issue by ssergio-ll** [varlesh/org.kde.plasma.digitalclock.wl#2]
Hello. 

Can you add option of "Keep open" to calendar like original of KDE Plasma?

Very thanks!

**Comment by varlesh** [comment]
added

**Comment by ssergio-ll** [comment]
I have install last version and i don't see option.

**Comment by varlesh** [comment]
I'm upload this just on KDE Store:
![image](https://user-images.githubusercontent.com/8083855/67003134-680bd780-f0ee-11e9-9a94-42233933a20e.png)

**Comment by ssergio-ll** [comment]
Now yes, but it don't visualize correctly. 
![imagen](https://user-images.githubusercontent.com/22059282/67003846-38a19e80-f0df-11e9-943a-36254c83730b.png)

**Comment by varlesh** [comment]
On settings available slider, for change font size... I thinking how solve this problem with margins

**Comment by varlesh** [comment]
@ssergio-ll I'm added slider for change horizontal Margin :
![image](https://user-images.githubusercontent.com/8083855/67005634-1cf4c300-f0f4-11e9-8cad-e8783f3d09bf.png)
PS: It's dirty code.... but now i don't know how solve this better. But it's worked ))

**Comment by varlesh** [comment]
@ssergio-ll  updated version already on KDE Store...
